// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0cgRzSKgQ_jhdvkXRk_6JbtiZbA9DSeo',
    appId: '1:824994590074:web:17e995f26d97f590277ac3',
    messagingSenderId: '824994590074',
    projectId: 'flash-aid',
    authDomain: 'flash-aid.firebaseapp.com',
    storageBucket: 'flash-aid.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT6WYTs42nPtER8eFe5jxmIInzkpaeJ90',
    appId: '1:824994590074:android:7837033df5e3cdbe277ac3',
    messagingSenderId: '824994590074',
    projectId: 'flash-aid',
    storageBucket: 'flash-aid.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALVuCtoImMl_xaXADC-qyIm3-9liXKiLA',
    appId: '1:824994590074:ios:1b5fe6b48d00edc5277ac3',
    messagingSenderId: '824994590074',
    projectId: 'flash-aid',
    storageBucket: 'flash-aid.firebasestorage.app',
    iosBundleId: 'com.example.flashAid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALVuCtoImMl_xaXADC-qyIm3-9liXKiLA',
    appId: '1:824994590074:ios:1b5fe6b48d00edc5277ac3',
    messagingSenderId: '824994590074',
    projectId: 'flash-aid',
    storageBucket: 'flash-aid.firebasestorage.app',
    iosBundleId: 'com.example.flashAid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0cgRzSKgQ_jhdvkXRk_6JbtiZbA9DSeo',
    appId: '1:824994590074:web:3dd71eb700105e10277ac3',
    messagingSenderId: '824994590074',
    projectId: 'flash-aid',
    authDomain: 'flash-aid.firebaseapp.com',
    storageBucket: 'flash-aid.firebasestorage.app',
  );
}
